name: Build omnisette-server

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build omnisette-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional rust targets
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Build for x86_64
        run: cargo build --release -C target-feature=+crt-static

      - name: Build for aarch64
        run: cross build --release --target aarch64-unknown-linux-gnu -C target-feature=+crt-static

      - name: Move and rename binaries
        run: |
          cp target/release/omnisette-server target/omnisette-server-linux-x86_64
          cp target/aarch64-unknown-linux-gnu/release/omnisette-server target/omnisette-server-linux-aarch64

      - name: Upload to new release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            target/omnisette-server-linux-x86_64
            target/omnisette-server-linux-aarch64
          body: |
            ## Changelog

            - TODO
